SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400
HORIZON_HEIGHT = 300
FPS = 60
SKY_COLOR = "light blue"
GROUND_COLOR = "dark green"
GAMEOVER_COLOR = "pink"
RESPAWN_TIME = 1500
BLACK_COLOR = "black"
GAME_TITLE = "Gra w ślimaka"
GAME_FAILURE = "Game Over"
PLAY_AGAIN = "Press mouse key to play again"
GAME_VICTORY = "You won the game, Congratulations !!!"
